### ISSUE TITLE
そろそろファイルの出力とパッケージマネージャを使用したモジュールのインストールをできるようにしたい

### ISSUE THREAD

**Issue by huequica** [huequica/project_kicker#26]
# summary

- #25 によってある程度本格的に実装が書けるようになったので書いていきたい

**Comment by huequica** [comment]
パッケージインストールのコマンド叩くときの子プロセス発行するモジュール選定

# cross-spawn
- [ESLint が使ってる](https://github.com/eslint/eslint/blob/main/bin/eslint.js#L128-L133)
- 型定義は [`@types/cross-spawn`](https://www.npmjs.com/package/@types/cross-spawn) にある。もしかしたらこのあたりでドツボはまるかも

# execa
- 公式に型情報を用意してる。安心度はこっちが高い

**Comment by huequica** [comment]
とりあえず execa を使う

**Comment by huequica** [comment]
execa が ESModules してやがるせいでテストが一生書けん

```
Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /home/huequica/Github.com/huequica/project_kicker/node_modules/execa/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import {Buffer} from 'node:buffer';
                                                                                      ^^^^^^

    SyntaxError: Cannot use import statement outside a module

    > 1 | import { execa } from 'execa';
        | ^
      2 |
      3 | export class PackageInstallerRepository {
      4 |   private readonly userSelectedPackageManager: 'npm' | 'yarn' = 'npm';

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1773:14)
      at Object.<anonymous> (src/repositories/packageInstaller.ts:1:1)
```
